
FROM rocker/shiny:latest
COPY . /srv/shiny-server/
WORKDIR /srv/shiny-server/
RUN apt-get update && apt-get install -y libsqlite3-dev
RUN Rscript init.R
EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
